AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth-resources

  SAM Template for auth resources

Parameters:
  Environment:
    Type: String
  AppName:
    Type: String
  Stage:
    Type: String
    Default: dev

Resources:
  Layers:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/layers/lambda_layers.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        DeploymentBucket: !Sub '/config/${Environment}/${AppName}/infra/bucket/artifacts'
  ApiCore:
    Type: AWS::Serverless::Application
    Properties:
      Location: core_api.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        AllowedOrigin: '*'
        CoreAppLayer: !GetAtt Layers.Outputs.CoreAppLayer
        DBClientLayer: !GetAtt Layers.Outputs.DBClientLayer
        VPCSecurityGroup: !Sub '/config/infra/${Environment}/${AppName}/security-group'
        VPCSubnets: !Sub '/config/infra/${Environment}/${AppName}/subnets'